version: "3.8"

services:
  postgres:
    image: postgres:15
    env_file:
      - ./config/.env.backend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: tokamaknetwork/trh-backend:1.0.0
    ports:
      - "8000:8000"
    env_file:
      - ./config/.env.backend
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - backend_storage:/app/storage

  ui:
    image: tokamaknetwork/trh-platform-ui:1.0.0
    ports:
      - "3000:3000"
    env_file:
      - ./config/.env.frontend
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  backend_storage:
